baseurl = "http://example.com/"
copyright = "&copy; Lorem ipsum ... and so on ..."
theme = "hamburg"
title = "Hamburg theme example"
[[menu.main]]
identifier = "about"
name = "About"
url = "pages/about"
weight = 1
[params]
mainSections = ["posts"]
subtitle = "The great example site of the hugo-hamburg-theme"
